name: install_plugin
description: A Flutter plugin for installing APKs on Android devices.
version: 2.0.0 # Major version bump for breaking changes
homepage: https://github.com/Gentleflow/install_plugin.git

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated SDK constraint
  flutter: ">=3.16.0" # Updated Flutter constraint

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Added for better code analysis